# Generated by Django 4.0.4 on 2022-04-25 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0003_location_meetup_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='title',
            field=models.CharField(max_length=55),
        ),
    ]
